//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIEN
    {
        public int MaPhieuThuTien { get; set; }
        public Nullable<int> SoTienNo { get; set; }
        public Nullable<int> SoTienThu { get; set; }
        public Nullable<int> MaDocGia { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
