USE [master]
GO

/****** Object:  Database [dbQLThuVien]    Script Date: 5/24/2020 6:07:58 PM ******/
CREATE DATABASE [dbQLThuVien]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbQLThuVien', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\dbQLThuVien.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbQLThuVien_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\dbQLThuVien_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbQLThuVien] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbQLThuVien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbQLThuVien] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbQLThuVien] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbQLThuVien] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbQLThuVien] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbQLThuVien] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbQLThuVien] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [dbQLThuVien] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbQLThuVien] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbQLThuVien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbQLThuVien] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbQLThuVien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbQLThuVien] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbQLThuVien] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbQLThuVien] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbQLThuVien] SET  ENABLE_BROKER 
GO

ALTER DATABASE [dbQLThuVien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbQLThuVien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbQLThuVien] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbQLThuVien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbQLThuVien] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbQLThuVien] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbQLThuVien] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbQLThuVien] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbQLThuVien] SET  MULTI_USER 
GO

ALTER DATABASE [dbQLThuVien] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbQLThuVien] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbQLThuVien] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbQLThuVien] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbQLThuVien] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbQLThuVien] SET  READ_WRITE 
GO


